name: PR Labels

on:
  pull_request_target:

jobs:
  labels:
    name: Ярлыки
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Устанавливает необходимые ярлыки
        uses: doka-guide/doka-labeler@c5888f4889a3fab53cb1ff4e10acd73e7d9e0aeb
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          strategy: append
          config: ".github/labeler.yml"
