name: PR Labels

on:
  pull_request_target:

jobs:
  labels:
    name: Ярлыки
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Устанавливает необходимые ярлыки
        uses: doka-guide/doka-labeler@2f572b781de7b1a13edb75caf8436588969046ca
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          strategy: append
          config: ".github/labeler.yml"
