name: PR Labels

on:
  pull_request_target:

jobs:
  labels:
    name: Ярлыки
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Устанавливает необходимые ярлыки
        uses: doka-guide/doka-labeler@8dda0017d2c7604a8acf80800232c5e6e2e89034
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          strategy: append
          config: ".github/labeler.yml"
