name: PR Labels

on:
  pull_request_target:

jobs:
  labels:
    name: Ярлыки
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Устанавливает необходимые ярлыки
        uses: doka-guide/doka-labeler@c8c0fcdad57a1aed4512add0d3c129c7990286d7
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          strategy: append
          config: ".github/labeler.yml"
